plugins:
  onedcu_enabled:
    default: true
    client: true
  onedcu_api_key:
    default: 39f810a82325454c449a42b849131b794d0d42f3cffac4e196a243c76c18304c
    client: true
  onedcu_user_api_key:
    default: ivanbacher
    client: true
  onedcu_now_on_cat_id: 
    default: 5
    client: true
  onedcu_coming_up_cat_id:
    default: 6
    client: true
  onedcu_deadline:
    default: "2019/05/10 10:00:00"
    client: true